class ColorsController < ApplicationController
  before_action :set_color, only: %i[ show edit update destroy ]

  # GET /colors or /colors.json
  def index
    @colors = Color.all
  end

  # GET /colors/1 or /colors/1.json
  def show
     if params[:showpic] == "true"
       @mycolor="""
  %% Generated by lilypond-book
  %% Options: [exampleindent=10.16\\mm,indent=0\\mm,inline=-0.3,line-width=160\\mm,paper-height=845.047\pt,paper-width=597.508\pt,papersize='(cons (* 597.508 pt) (* 845.047 pt))]
  \\include \"lilypond-book-preamble.ly\"
  
  
  % ****************************************************************
  % Start cut-&-pastable-section
  % ****************************************************************
  
  #(ly:set-option 'eps-box-padding 0.000100)
  
  
  
  \\paper {
    #(set-paper-size '(cons (* 597.508 pt) (* 845.047 pt)))
    indent = 0\\mm
    line-width = 160\\mm
    % offset the left padding, also add 1mm as lilypond creates cropped
    % images with a little space on the right
    line-width = #(- line-width (* mm  0.000100) (* mm 1))
  }
  
  \\layout {
    
  }
  
  
  
  
  % ****************************************************************
  % ly snippet:
  % ****************************************************************
  \\sourcefileline 11
  
      \\markup
        \\override #'(box-padding . 0)
        \\box \\with-color #(x11-color '#{@color.name})
          \\filled-box #'(0 . 2) #'(0 . 2) #0
  
  
  % ****************************************************************
  % end ly snippet
  % ****************************************************************
  
  """
      File.write("./public/uploads/color#{@color.id}.ly","<lilypond staffsize=\"34\">"+@mycolor+"</lilypond>")
      x=`(cd #{Rails.root.to_s}/public/uploads && lilypond-book color#{@color.id}.ly -f html --output macouleur#{@color.id})`
      @doc=Nokogiri::HTML(File.read(Rails.root.to_s+"/public/uploads/macouleur#{@color.id}/color#{@color.id}.html"))
      @pic=@doc.css("img")[0].attributes["src"].value
    end
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit
  end

  # POST /colors or /colors.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: "Color was successfully created." }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new, status: :unprocessable_content }
        format.json { render json: @color.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /colors/1 or /colors/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to @color, notice: "Color was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit, status: :unprocessable_content }
        format.json { render json: @color.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /colors/1 or /colors/1.json
  def destroy
    @color.destroy!

    respond_to do |format|
      format.html { redirect_to colors_path, notice: "Color was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def color_params
      params.require(:color).permit(:name)
    end
end
